/**
 * Generates src/replay/demo-data.ts from the Kaveri seed, so the UI replay
 * shows the same vendors, bills and amounts as the mock company.
 * Run: pnpm --filter @theseus/web gen:demo   (a test checks it stays in sync)
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { demoDataFromSeed } from "../test/demo-source.ts";

const out = fileURLToPath(new URL("../src/replay/demo-data.ts", import.meta.url));
writeFileSync(
  out,
  `// GENERATED by scripts/gen-demo-data.ts from the Kaveri seed. Do not edit by hand.\nimport type { DemoData } from "./types.ts";\n\nexport const DEMO_DATA: DemoData = ${JSON.stringify(demoDataFromSeed(), null, 2)};\n`,
);
console.log(`wrote ${out}`);
