import { existsSync } from "node:fs";
import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { AlignmentType, Document, HeadingLevel, Packer, Paragraph, Table, TableCell, TableRow, TextRun, WidthType } from "docx";
import ExcelJS from "exceljs";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { KaveriState } from "./domain.ts";
import { BIDDERS, COMPANY } from "./seed/scenario.ts";

/**
 * The employee's local workspace: real files on disk next to the websites.
 *   Vendor Desk/Vendor Register.xlsx     team tracker (open cases for T-2026-14 + history)
 *   Vendor Desk/Policies/Vendor Master Policy.pdf   the SOP the agent must read and follow
 *   Vendor Desk/Templates/*.docx         templates the agent fills (docxtemplater {tags})
 *   Vendor Desk/Bidders/                 where downloaded bidder documents go
 *   Payments/W41/                        batch export, bank upload CSV, report
 *   Outbox/                              generated letters / drafts
 * Regenerated on every world reset. A marker file guards deletion: we only
 * ever wipe a folder that this generator created.
 */
export const MARKER = ".kaveri-workspace";
const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");
export const DEFAULT_WORKSPACE = process.env.KAVERI_WORKSPACE ?? join(REPO_ROOT, "workspace");

export const WORKSPACE_FILES = {
  register: "Vendor Desk/Vendor Register.xlsx",
  policy: "Vendor Desk/Policies/Vendor Master Policy.pdf",
  empanelmentTemplate: "Vendor Desk/Templates/Empanelment Note.docx",
  reportTemplate: "Vendor Desk/Templates/Payment Integrity Report.docx",
  biddersDir: "Vendor Desk/Bidders",
  batchDir: "Payments/W41",
  outbox: "Outbox",
} as const;

/** Top-level entries a generated workspace (and the agents working in it) can contain. */
const OWN_ENTRIES = new Set([MARKER, "Vendor Desk", "Payments", "Outbox", "Drafts", "Attachments", "desktop.ini", ".DS_Store"]);

export async function generateWorkspace(state: KaveriState, dir = DEFAULT_WORKSPACE): Promise<string> {
  if (existsSync(dir)) {
    const entries = await readdir(dir);
    // Ours if it has the marker, or (a reset that was interrupted) only folders we create ourselves.
    const ours = entries.includes(MARKER) || entries.every((e) => OWN_ENTRIES.has(e));
    if (!ours) throw new Error(`Refusing to reset ${dir}: it isn't a Kaveri workspace (no ${MARKER} marker). Move it away or set KAVERI_WORKSPACE.`);
    // Empty it but keep the folder itself (the app may be watching it), the user's attachments and the
    // marker (so a reset that fails half-way still recognises the folder next time).
    const stuck: string[] = [];
    for (const e of entries) {
      if (e === "Attachments" || e === MARKER) continue;
      // Windows: a folder being watched, or a file open in Excel/Word, can refuse deletion for a moment.
      await rm(join(dir, e), { recursive: true, force: true, maxRetries: 8, retryDelay: 150 }).catch(() => stuck.push(e));
    }
    if (stuck.length)
      throw new Error(`Couldn't clear ${stuck.join(", ")} in the workspace. Is a file from it open in Excel, Word or a PDF viewer? Close it and press ↻ again.`);
  }
  for (const d of [WORKSPACE_FILES.biddersDir, WORKSPACE_FILES.batchDir, WORKSPACE_FILES.outbox, "Vendor Desk/Policies", "Vendor Desk/Templates"])
    await mkdir(join(dir, d), { recursive: true });
  await writeFile(join(dir, MARKER), `Generated by Kaveri for scenario date ${state.today}. Safe to delete; regenerated on world reset.\n`);
  await writeFile(join(dir, WORKSPACE_FILES.register), await vendorRegister(state));
  await writeFile(join(dir, WORKSPACE_FILES.policy), await policyPdf());
  await writeFile(join(dir, WORKSPACE_FILES.empanelmentTemplate), await empanelmentTemplate());
  await writeFile(join(dir, WORKSPACE_FILES.reportTemplate), await reportTemplate());
  return dir;
}

/* ------------------------------------------------------- Vendor Register */

export const REGISTER_COLUMNS = [
  "Case ID", "Tender", "Bidder", "Received on", "Docs complete", "GSTIN check", "PAN match", "Bank (penny-drop)",
  "MSME (Udyam)", "Duplicates / conflicts", "Debarment", "ERP vendor id", "Status", "Notes",
] as const;

async function vendorRegister(state: KaveriState): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Kaveri Infra · Vendor Desk";
  const cases = wb.addWorksheet("Onboarding cases", { views: [{ state: "frozen", ySplit: 1 }] });
  cases.columns = REGISTER_COLUMNS.map((h) => ({ header: h, key: h, width: h === "Notes" ? 48 : h === "Bidder" ? 34 : 16 }));
  // History: closed cases from earlier tenders (filler vendors that are now active).
  const awarded = state.tenders.filter((t) => t.status === "awarded");
  let n = 101;
  for (const t of awarded)
    for (const name of t.qualifiedBidders) {
      const v = state.vendors.find((x) => x.legalName === name);
      cases.addRow({
        "Case ID": `VC-2026-${n++}`, Tender: t.id, Bidder: name, "Received on": "2026-05-1" + (n % 9), "Docs complete": "Yes",
        "GSTIN check": v?.gstin ? "Active" : "Not registered (declaration)", "PAN match": "Yes", "Bank (penny-drop)": "Name matches",
        "MSME (Udyam)": v?.udyam?.category ?? "none", "Duplicates / conflicts": "None", Debarment: "Clear", "ERP vendor id": v?.id ?? "",
        Status: "Closed: Active", Notes: "",
      });
    }
  // Open cases for this week's work.
  const received: Record<string, string> = { A: "2026-10-02", B: "2026-10-02", C: "2026-10-03" };
  for (const [k, b] of Object.entries(BIDDERS))
    cases.addRow({ "Case ID": `VC-2026-${n++}`, Tender: "T-2026-14", Bidder: b.legalName, "Received on": received[k], Status: "Docs received", Notes: "" });
  cases.getRow(1).font = { bold: true };
  cases.getRow(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFE8EEF5" } };
  cases.autoFilter = { from: "A1", to: "N1" };

  const log = wb.addWorksheet("Bank change log", { views: [{ state: "frozen", ySplit: 1 }] });
  log.columns = ["Date", "Vendor ID", "Vendor", "Old account", "New account", "Requested via", "Call-back ref", "Verified by"].map((h) => ({ header: h, key: h, width: 20 }));
  for (const v of state.vendors)
    for (const h of v.history.filter((x) => x.field === "bank")) {
      const before = h.before as { accountNumber: string; ifsc: string };
      const after = h.after as { accountNumber: string; ifsc: string };
      const cb = /call-back (CB-\d+)/.exec(h.source ?? "")?.[1] ?? "";
      log.addRow({
        Date: h.at.slice(0, 10), "Vendor ID": v.id, Vendor: v.legalName, "Old account": `${before.accountNumber} / ${before.ifsc}`,
        "New account": `${after.accountNumber} / ${after.ifsc}`, "Requested via": h.source?.startsWith("email") ? h.source : "Letter",
        "Call-back ref": cb, "Verified by": cb ? h.by.replace("user:", "") : "",
      });
    }
  log.getRow(1).font = { bold: true };

  const help = wb.addWorksheet("How to use");
  help.getColumn(1).width = 110;
  [
    "Vendor Desk register: one row per onboarding case. Update the check columns as you verify each document.",
    "Status values: Docs received → Under verification → Pending approval → Closed: Active | Parked (reason in Notes) | Escalated (reason in Notes).",
    "Every bank change must have a call-back reference (phone call to the number already on record). See the Vendor Master Policy.",
  ].forEach((t) => help.addRow([t]));
  return Buffer.from(await wb.xlsx.writeBuffer());
}

/* ---------------------------------------------------------- Policy (PDF) */

export const POLICY_SECTIONS: Array<{ title: string; rules: string[] }> = [
  {
    title: "1. Purpose and scope",
    rules: [
      "This policy governs the vendor master and pre-payment checks at Kaveri Infra Pvt Ltd. It applies to all vendors, contractors and suppliers.",
      "Payments may only be made to vendors that are Active in the ERP and to the bank account recorded in the vendor master.",
    ],
  },
  {
    title: "2. Vendor registration (empanelment)",
    rules: [
      "2.1 Required documents: GST registration certificate (or a declaration if not registered), PAN card, cancelled cheque or bank letter, Udyam certificate if the vendor is an MSME.",
      "2.2 The GSTIN must be Active on the GST portal; the PAN inside the GSTIN (characters 3-12) must equal the PAN card; the GSTIN state code must match the registered address.",
      "2.3 The bank account must be validated by penny-drop. The name at bank must match the legal name. For a proprietorship, an account in the proprietor's own name is acceptable with a signed declaration.",
      "2.4 Check for duplicates (same PAN, GSTIN or bank account, or a very similar name) and for conflicts of interest (address or bank account matching any employee).",
      "2.5 Check the debarment register. Debarred parties must not be registered.",
      "2.6 Create the vendor as Pending. Activation requires approval by a different person (maker-checker). Record the case in the Vendor Register.",
      "2.7 If a check fails, park the case with the reason, inform the requester and ask the bidder for corrected documents. Escalate conflicts of interest to the Finance Head.",
    ],
  },
  {
    title: "3. Bank detail changes",
    rules: [
      "3.1 Never act on an email alone. Treat every bank-change request as high risk, whatever the sender.",
      "3.2 Immediately hold all payments to the vendor until the request is resolved.",
      "3.3 Verify by a call-back to the phone number already in the vendor master, never a number given in the request. Record the call-back reference.",
      "3.4 Validate the new account by penny-drop; the name at bank must match the vendor's legal name.",
      "3.5 Red flags: sender domain different from the one on record, urgency or secrecy, request just before a large payment, a second change within 60 days.",
      "3.6 Apply the change only after call-back and approval by the Finance Head. Log it in the Bank change log.",
    ],
  },
  {
    title: "4. Pre-payment integrity check",
    rules: [
      "4.1 Every line of a payment batch must be checked before release: vendor Active and not debarred; pay-to account equal to the vendor master; no bank change in the last 30 days without a recorded call-back; no duplicate bill; correct TDS; MSME deadlines.",
      "4.2 TDS on contractors (Income-tax Act 2025, Section 393, formerly 194C): 1% for individuals/HUF (PAN 4th letter P or H), 2% for others, 20% if no valid PAN. Applies if a single payment exceeds Rs. 30,000 or the year's total exceeds Rs. 1,00,000.",
      "4.3 MSME (Section 43B(h)): pay micro and small enterprises within 15 days of acceptance, or the agreed date if there is a written agreement, never later than 45 days. Lines due within 3 days must be flagged as priority.",
      "4.4 Each line is Cleared, Held (with a written reason) or Corrected (with the correction shown). When in doubt, hold.",
      "4.5 The bank upload file contains only cleared and corrected lines, at net amounts. Upload is done by the AP maker; authorisation by the Finance Head (checker).",
      "4.6 Send the Finance Head a Payment Integrity Report: totals, held lines with reasons, corrections, MSME priorities.",
    ],
  },
  {
    title: "5. Records",
    rules: [
      "Keep all downloaded documents in Vendor Desk/Bidders/<bidder name>/ and batch working files in Payments/<week>/.",
      "Use the templates in Vendor Desk/Templates for empanelment notes and integrity reports.",
    ],
  },
];

async function policyPdf(): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  doc.setTitle("Vendor Master Policy");
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const W = 595, H = 842, M = 56, maxW = W - 2 * M;
  let page = doc.addPage([W, H]);
  let y = H - M;
  const wrap = (text: string, f: typeof font, size: number) => {
    const words = text.split(" ");
    const lines: string[] = [];
    let cur = "";
    for (const w of words) {
      const next = cur ? `${cur} ${w}` : w;
      if (f.widthOfTextAtSize(next, size) > maxW) (lines.push(cur), (cur = w));
      else cur = next;
    }
    if (cur) lines.push(cur);
    return lines;
  };
  const write = (text: string, f = font, size = 10.5, gap = 4) => {
    for (const line of wrap(text, f, size)) {
      if (y < M + 30) ((page = doc.addPage([W, H])), (y = H - M));
      page.drawText(line, { x: M, y, size, font: f, color: rgb(0.1, 0.1, 0.1) });
      y -= size + gap;
    }
  };
  write(COMPANY.name, bold, 16);
  write("Vendor Master Policy · Finance & Accounts · Version 3.2 · Effective 1 April 2026", font, 10);
  y -= 10;
  for (const s of POLICY_SECTIONS) {
    y -= 6;
    write(s.title, bold, 12.5, 6);
    for (const r of s.rules) (write(r), (y -= 4));
  }
  y -= 10;
  write("Approved by: Anil Shetty, Finance Head. Owner: Accounts Payable.", font, 9);
  write("SPECIMEN: fictional document generated for the Theseus Mini simulation.", font, 8);
  return doc.save({ useObjectStreams: false });
}

/* ------------------------------------------------------ Word templates */

const p = (text: string, opts: { bold?: boolean; heading?: (typeof HeadingLevel)[keyof typeof HeadingLevel]; size?: number } = {}) =>
  new Paragraph({ ...(opts.heading ? { heading: opts.heading } : {}), spacing: { after: 120 }, children: [new TextRun({ text, bold: opts.bold, size: opts.size })] });

const kvTable = (rows: Array<[string, string]>) =>
  new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: rows.map(([k, v]) => new TableRow({ children: [new TableCell({ width: { size: 35, type: WidthType.PERCENTAGE }, children: [p(k, { bold: true })] }), new TableCell({ children: [p(v)] })] })),
  });

/** Fields: docxtemplater tags in {curly} braces. Each tag sits in ONE text run so it always renders. */
export const EMPANELMENT_TAGS = [
  "case_id", "tender_id", "legal_name", "pan", "gstin", "gstin_status", "address", "bank_account", "ifsc", "name_at_bank",
  "udyam_number", "msme_category", "duplicate_check", "conflict_check", "debarment_check", "erp_vendor_id",
  "recommendation", "prepared_by", "date",
] as const;

async function empanelmentTemplate(): Promise<Buffer> {
  const doc = new Document({
    creator: "Kaveri Infra · Vendor Desk",
    title: "Empanelment Note",
    sections: [
      {
        children: [
          new Paragraph({ alignment: AlignmentType.LEFT, heading: HeadingLevel.TITLE, children: [new TextRun({ text: "Empanelment Note" })] }),
          p(`${COMPANY.name} · Vendor Desk · Case {case_id} · Tender {tender_id}`),
          p("1. Vendor", { heading: HeadingLevel.HEADING_2 }),
          kvTable([["Legal name", "{legal_name}"], ["PAN", "{pan}"], ["GSTIN", "{gstin}"], ["Registered address", "{address}"]]),
          p("2. Verification", { heading: HeadingLevel.HEADING_2 }),
          kvTable([
            ["GST portal status", "{gstin_status}"],
            ["Bank account / IFSC", "{bank_account} / {ifsc}"],
            ["Name at bank (penny-drop)", "{name_at_bank}"],
            ["Udyam / MSME category", "{udyam_number} / {msme_category}"],
            ["Duplicate check", "{duplicate_check}"],
            ["Conflict of interest check", "{conflict_check}"],
            ["Debarment register", "{debarment_check}"],
          ]),
          p("3. Issues found", { heading: HeadingLevel.HEADING_2 }),
          p("{#issues}• {.}"),
          p("{/issues}"),
          p("4. Recommendation", { heading: HeadingLevel.HEADING_2 }),
          p("{recommendation}"),
          kvTable([["ERP vendor id", "{erp_vendor_id}"], ["Prepared by", "{prepared_by}"], ["Date", "{date}"], ["Approved by (checker)", ""]]),
        ],
      },
    ],
  });
  return Buffer.from(await Packer.toBuffer(doc));
}

export const REPORT_TAGS = ["batch_id", "date", "prepared_by", "lines_total", "cleared_count", "held_count", "corrected_count", "upload_total", "upload_file", "summary"] as const;

async function reportTemplate(): Promise<Buffer> {
  const doc = new Document({
    creator: "Kaveri Infra · Accounts Payable",
    title: "Payment Integrity Report",
    sections: [
      {
        children: [
          new Paragraph({ heading: HeadingLevel.TITLE, children: [new TextRun({ text: "Payment Integrity Report" })] }),
          p(`${COMPANY.name} · Batch {batch_id} · {date} · prepared by {prepared_by}`),
          p("Summary", { heading: HeadingLevel.HEADING_2 }),
          p("{summary}"),
          kvTable([
            ["Lines checked", "{lines_total}"],
            ["Cleared", "{cleared_count}"],
            ["Corrected", "{corrected_count}"],
            ["Held", "{held_count}"],
            ["Bank upload file", "{upload_file}"],
            ["Upload total (net)", "{upload_total}"],
          ]),
          p("Held lines", { heading: HeadingLevel.HEADING_2 }),
          p("{#held}• {line} · {vendor} · {amount}: {reason}"),
          p("{/held}"),
          p("Corrections", { heading: HeadingLevel.HEADING_2 }),
          p("{#corrected}• {line} · {vendor}: {change}"),
          p("{/corrected}"),
          p("MSME priority", { heading: HeadingLevel.HEADING_2 }),
          p("{#priority}• {line} · {vendor}: due {due}"),
          p("{/priority}"),
          p("For release by the Finance Head after review. The bank upload is authorised on the bank portal by the checker."),
        ],
      },
    ],
  });
  return Buffer.from(await Packer.toBuffer(doc));
}
